info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    build.version: ${project.version}
  app:
    name: Platform
    description: The platform
    version: ${project.version}

spring:
  thymeleaf:
    cache: false
